version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
      - pgsql
    env_file:
      - .env
    volumes:
      - ${SF_APP_PATH}:/var/www/app:cached
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    container_name: nginx
    restart: on-failure
    networks:
      - internal
    links:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      EXTERNAL_XDEBUG_PORT: ${EXTERNAL_XDEBUG_PORT}
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - ${SF_APP_PATH}:/var/www/app:cached
      - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./docker/php/conf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
    ports:
      - "9000:9000"
    working_dir: /var/www/app
    container_name: php
    networks:
      - internal
    links:
      - pgsql

  pgsql:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    container_name: pgsql
    networks:
      - internal
    volumes:
      - pgsql-data:/var/lib/postgresql/data

networks:
  internal:
    name: app-network

volumes:
  pgsql-data:
    name: pgsql-data
